### PR TITLE
Fix positioning on linux when using non-1 scale factor

### PR DESCRIPTION
**Pull request by Nephyrin**
Awakened PoE Trade gets the wrong window bounds in KDE 6.6 when scaling is active.  This can be worked around with `--force-device-scale-factor=1`, but this also creates unscaled UI in the app.

screenToDipRect is not supported on linux, though screenToDipPoint is.  In my testing with mixed-scaling displays, just translating via Point is always correct, including on e.g. overlapping monitors of different values.  I suspect this is due to multi-screen coordinates being implemented more transparently on linux, but I didn't dig further.

Tested on KDE when forcing X11 via `XDG_SESSION_TYPE=x11 ./awakened-poe-trade --ozone-platform=x11`

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -163,6 +163,10 @@ class OverlayControllerGlobal {
 
     if (process.platform === 'win32') {
       lastBounds = screen.screenToDipRect(this.electronWindow, this.targetBounds)
+    } else if (isLinux) {
+      let scaledXY = screen.screenToDipPoint({ x: lastBounds.x, y: lastBounds.y })
+      let scaledSize = screen.screenToDipPoint({ x: lastBounds.width, y: lastBounds.height })
+      lastBounds = { width: scaledSize.x, height: scaledSize.y, ...scaledXY };
```
Comment (SnosMe) [inline src/index.ts]: I think you want 

```ts
  const tl = screen.screenToDipPoint({ x: lastBounds.x, y: lastBounds.y })
  const br = screen.screenToDipPoint({ x: lastBounds.x + lastBounds.width, y: lastBounds.y + lastBounds.height })
  lastBounds = { x: tl.x, y: tl.y, width: br.x - tl.x, height: br.y - tl.y }
```

and check if this still work for you

Comment (Nephyrin) [reply src/index.ts]: This version also works, though in X11 land there's no concept of per-monitor scaling so the ratio should be universal.

Doing testing with some prints with the game maximized, I see

Game on 2.0x scale monitor with a 1.5x monitor peer to the left:
```
Scaling from: 3840.0 / 2160.0 @ 5120.0, 0.0
Scaling to: 1920.0 / 1080.0 @ 2560.0, 0.0, RATIO 2.00
```

Game on 1.5x scale monitor with a 2.0x monitor peer to the right:
```
Scaling from: 5120.0 / 2880.0 @ 0.0, 0.0
Scaling to: 2560.0 / 1440.0 @ 0.0, 0.0, RATIO 2.00
```

Game on 1.5x scale monitor with a 1.5x monitor peer:
Now all the 1.5 scale monitors are shown the 1/1.5 coordinate world
```
Scaling from: 3840.0 / 2160.0 @ 3840.0, 0.0
Scaling to: 2560.0 / 1440.0 @ 2560.0, 0.0, RATIO 1.50
```

... So it seems like CEF/chromium is seeing a world where the monitors are physically different resolutions at the same ratio, which is probably how KDE pushes the concept of per-screen scaling down to X11 clients.

For wayland clients this would presumably be different, though using `x+width` per above would break as soon as a window's BR point was on a different display from TL.  Presumably you could steal the ratio the TL point was scaled by and use it on the width/height values, but that's assuming the window is using the same coordinate space for both values -- KDE translates a window's scale factor based on its center point, so who knows what coordinates are actually correct.

I think either version is fine to merge now, and probably proper-wayland-support will need this all fixed anyway. (Also CEF reports it lacks proper wayland support for these functions, ha)

Comment (Nephyrin) [reply src/index.ts]: I updated this with your version and my best-effort comment explaining what I think the situation is for future generations debugging this on wayland.

Feel free to edit/change further, though

**Comment by pekac45** [comment]
@SnosMe @Nephyrin  I think this PR introduced a regression.

When I try to install 4.1.0 to get my cast changes in (https://github.com/SnosMe/electron-overlay-window/pull/52) 

I get this error:

```
FATAL ERROR: tsfn_to_js_proxy napi_call_function
----- Native stack trace -----
```


**Tested on:**

| | |
|---|---|
| **OS** | CachyOS Linux (`6.19.12-1-cachyos`) |
| **DE / WM** | KDE Plasma on Wayland (`wayland-0`) |
| **Xwayland** | 24.1.9 (`DISPLAY :0`, rootless, ei-portal enabled) |
| **CPU** | AMD Ryzen 7 5800X3D |
| **GPU** | AMD Radeon RX 9070 XT (Navi 48 / GFX1201) |
| **Driver** | Mesa 26.0.4 — radeonsi (OpenGL) · RADV GFX1201 (Vulkan 1.4.335) |
| **Kernel** | 6.19.12-1-cachyos (PREEMPT_DYNAMIC) |
| **RAM** | 64 GB (39 GB available during test) |
| **Steam / Proton** | LegacyRuntime |
| **Steam App ID** | 238960 (Path of Exile 2) |
| **Window mode** | Windowed/borderless (`_NET_WM_WINDOW_TYPE_NORMAL`, no fullscreen state) |
| **Wine flip model** | Disabled (`_WINE_ALLOW_FLIP = 0`) |
| **Locale** | `en_US.UTF-8` |

when I revert 3064b782105f57e518d474e0b6e85586a7819328 it works.

**Comment by SnosMe** [comment]
@pekac45 Hmm, for me the fix works without issues, and it's indeed needed.
Can you wrap all code inside `updateOverlayBounds` with

```
try {} catch (e) { console.log(e) }
```

I wonder which Electron function throws error from stacktrace.

---

Without the fix (DPR 1.25)

image

---

With the fix:

image

**Comment by pekac45** [comment]
@SnosMe When I run in with demo electron app from package.json it works fine with no exceptions thrown.

However I am getting this:

```
Catch block - updating overlay bounds
TypeError: electron_1.screen.screenToDipPoint is not a function
    at OverlayControllerGlobal.updateOverlayBounds (/home/mcachy/code/electron-overlay-window/dist/index.js:122:46)
    at EventEmitter.<anonymous> (/home/mcachy/code/electron-overlay-window/dist/index.js:56:18)
    at EventEmitter.emit (node:events:530:35)
    at OverlayControllerGlobal.handler (/home/mcachy/code/electron-overlay-window/dist/index.js:144:29)
```

when I run it from https://github.com/scalpelpoe/scalpel as a local package

**Comment by SnosMe** [comment]
@pekac45 you have electron 32, and this api was added in 35+

**Comment by pekac45** [comment]
thank you, I'll test it after bumping
